services:
  web:
    build:
      context: ./web
    image: mlchals/chatbot:1.0
    container_name: flask
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app_network
    environment:
      - FLASK_APP=api.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - DEBUG=True

  ollama:
    image: mlchals/ollama:1.0
    container_name: ollama
    ports:
      - "11434:11434"
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
